services:
  postgres:
    image: postgres:latest
    container_name: postgres-quan-ly-nhan-su
    volumes:
      - ./data/data_db:/var/lib/postgresql/data
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin1234
      POSTGRES_DB: quan_ly_nhan_su
    ports:
      - '5432:5432'
    networks:
      - node-networks
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U admin -d quan_ly_nhan_su']
      interval: 10s
      retries: 5
      start_period: 10s

  backend:
    container_name: quan-ly-nhan-su-backend
    build: ./
    ports:
      - '8080:8080'
    networks:
      - node-networks
    depends_on:
      postgres:
        condition: service_healthy

networks:
  node-networks:
    driver: bridge
