services:
  postgres:
    image: postgres:latest # docker hub
    container_name: postgres-quan-ly-nhan-su # ten container
    volumes: # backup du lieu
      - ./data/data_db:/var/lib/postgresql/data
      - ./data/docker-entrypoint-initdb.d/:/docker-entrypoint-initdb.d/
    restart: always # khi ma loi tu dong chay lai, khi tat may mo lai
    environment: # bien moi truong
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin1234
      POSTGRES_DB: quan_ly_nhan_su
    ports:
      - '5432:5432'
    networks: # mang chung
      - node-networks
    healthcheck: # kiem tra trang thai
      test: ['CMD-SHELL', 'pg_isready -U admin -d quan_ly_nhan_su']
      interval: 10s
      retries: 5
      start_period: 10s

  backend:
    container_name: quan-ly-nhan-su-backend
    build: ./
    ports:
      - '8080:8080'
    networks:
      - node-networks
    depends_on:
      postgres:
        condition: service_healthy

networks:
  node-networks:
    driver: bridge # host
