services:
  postgres:
    image: postgres:latest
    container_name: postgres-quan-ly-nhan-su
    restart: always
    volumes:
      - ./data/data_db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin1234
      POSTGRES_DB: quan_ly_nhan_su
    ports:
      - '5432:5432'
    networks:
      - node-networks

networks:
  node-networks:
    driver: bridge
